<div class="container">
    <h1 style="text-align: center">Login</h1>
<!--    --><?php
//    if($flash -> output())
//    {
//        echo $flash->output();
//    };?>
    <form action="/Phalcon/demoLogin/user/authorize" method="post">
        <p>
        <div class="form-group row">
            <div class="col-sm-2 col-form-label">Email:</div>
            <div class="col-sm-10">
                <?php echo $form->render('email',[
                    'placeholder' => 'email',
                    'class' => 'form-control'
                ]);?>
            </div>
        </div>
        </p>
        <p>
        <div class="form-group row">
            <div class="col-sm-2 col-form-label">Password:</div>
            <div class="col-sm-10">
                <?php echo $form->render('password',[
                    'maxlength'   => 30,
                    'placeholder' => 'Password',
                    'class' => 'form-control'
                ]);?>
            </div>
        </div>
        </p>
        <p>
        <div class="row ml-1 text-center " style="display: flex; justify-content: center">
            <input type='submit' value='Login' class="btn btn-info"/>
            <button type="button" class="btn btn-danger ml-3" onclick="window.history.go(-1); return false;">Cancel</button>
        </div>
        </p>
    </form>
</div>