<div class="container">
    <h1 style="text-align: center">Register</h1>
    <form action="/Phalcon/demoLogin/user/create" method="post">
        <p>
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">UserName:</div>
                <div class="col-sm-10">
                    <?php echo $form->render('name',[
                        'maxlength'   => 30,
                        'placeholder' => 'name',
                        'class' => 'form-control'
                    ]);?>
                </div>
            </div>
        </p>
        <p>
            <div class="form-group row">
            <div class="col-sm-2 col-form-label">Email:</div>
            <div class="col-sm-10">
                <?php echo $form->render('email',[
                    'placeholder' => 'email',
                    'class' => 'form-control'
                ]);?>
            </div>
        </div>
        </p>
        <p>
            <div class="form-group row">
            <div class="col-sm-2 col-form-label">Phone:</div>
            <div class="col-sm-10">
                <?php echo $form->render('phone',[
                    'maxlength'   => 12,
                    'placeholder' => 'Phone Number',
                    'class' => 'form-control'
                ]);?>
            </div>
        </div>
        </p>
        <p>
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">Password:</div>
                <div class="col-sm-10">
                    <?php echo $form->render('password',[
                        'maxlength'   => 30,
                        'placeholder' => 'Password',
                        'class' => 'form-control'
                    ]);?>
                </div>
            </div>
        </p>
        <p>
            <div class="row ml-1 text-center " style="display: flex; justify-content: center">
                <input type='submit' value='Register' class="btn btn-info"/>
                <button type="button" class="btn btn-danger ml-3" onclick="window.history.go(-1); return false;">Cancel</button>
            </div>
        </p>
    </form>
</div>